version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"  # map container port 8000 to host port 8000
    environment:
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # volumes for development to mount local changes
    volumes:
       - ./backend/app:/app/app
       - ./frontend:/app/static/frontend
       - ./index.html:/app/index.html
