services:
  - type: web
    name: nyc-summative-backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
      - key: DB_PATH
        value: /app/nyc_train.db
